on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

name: Qemu metrics checks
jobs:
  
  boot-time-checks:
    runs-on: ubuntu-20.04
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      -name: Checkout code
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
         path: ./src/github.com/${{ github.repository }}
      -name: run launch times if
       run: |
         cd ${GOPATH}/src/github.com/${{ github.repository }} && echo $PWD && ls -lh
