on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

name: Qemu metrics checks
jobs:
  boot-time-checks:
    runs-on: ubuntu-20.04
    env:
      GOPATH: ${{ github.workspace }}
      TEST_FOLDER: ${GOPATH}/src/github.com/${{ github.repository }}/tests/metrics/
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: ./src/github.com/${{ github.repository }}
    - name: run launch times
      run: |
        cd ${TEST_FOLDER} && echo $PWD && bash time/launch_times.sh -i public.ecr.aws/ubuntu/ubuntu:latest -n 20

    - name: clean environment
      run: |
        cd ${GOPATH}/src/github.com/${{ github.repository }} && git clean -xfd
